#
#	Makefile for Windows Visual Studio projects
#
#	Copyright (c) Embedthis Software LLC, 2003-2009. All Rights Reserved.
#

PRE_DIRS	= appweb-static appweb-dynamic

include     .makedep

cleanExtra:
	rm -rf appweb*/Win32
