#
#	Makefile for the MPR
#
#	Copyright (c) Embedthis Software LLC, 2003-2011. All Rights Reserved.
#

include 	.makedep

compileFirst:	
	$(MAKE) -f Makefile.all

cleanExtra:
	$(MAKE) -f Makefile.all clean

