#
#	Makefile for Ejscript
#
#	Copyright (c) Embedthis Software LLC, 2003-2011. All Rights Reserved.
#

include 	.makedep

compileFirst:	
	$(MAKE) -f Makefile.all

cleanExtra:
	$(MAKE) -f Makefile.all clean

modules:
	$(MAKE) -f Makefile.all modules


#
#   Local variables:
#   tab-width: 4
#   c-basic-offset: 4
#   End:
#   vim: sw=4 ts=4
#
