#
#	Makefile -- Releases makefile
#
#	Copyright (c) Embedthis Software LLC, 2003-2011. All Rights Reserved.
#

include 	.makedep

cleanExtra:
	@rm -fr *.gz *.dmg *.exe *.zip *.rpm *.txt

#
#   Local variables:
#   tab-width: 4
#   c-basic-offset: 4
#   End:
#   vim: sw=4 ts=4
#
