/*
 * Acme.slots.h -- Property slot definitions for the "Acme" module
 *
 * This file is generated by ec
 *
 * Slot definitions. Version 3.2.0.
 */

#ifndef _h_SLOTS_AcmeSlots
#define _h_SLOTS_AcmeSlots 1


/**
 * Slots for the "Acme" module 
 */


/**
 *   Class property slots for the "global" class 
 */

/**
 * Instance slots for "global" type 
 */


/**
 *   Class property slots for the "Rocket" class 
 */
#define ES_Acme_Rocket__origin                                         6
#define ES_Acme_Rocket_Rocket                                          6
#define ES_Acme_Rocket_countdown                                       7
#define ES_Acme_Rocket_blastoff                                        8
#define ES_Acme_Rocket_NUM_CLASS_PROP                                  9

/**
 * Instance slots for "Rocket" type 
 */
#define ES_Acme_Rocket_NUM_INSTANCE_PROP                               0

/**
 * 
 *    Local slots for methods in type Rocket 
 */
#define ES_Acme_Rocket_blastoff_v                                      0
#define ES_Acme_Rocket_blastoff_delay                                  1

#define _ES_CHECKSUM_Acme 6868

#endif
