/*
 * ejs.web.slots.h -- Property slot definitions for the "ejs.web" module
 *
 * This file is generated by ec
 *
 * Slot definitions. Version 1.0.0.
 */

#ifndef _h_SLOTS_EjsWebSlots
#define _h_SLOTS_EjsWebSlots 1


/**
 * Slots for the "ejs.web" module 
 */


/**
 *   Class property slots for the "global" class 
 */

/**
 * Instance slots for "global" type 
 */

/**
 * 
 *    Local slots for methods in type global 
 */


/**
 *   Class property slots for the "Cache" class 
 */
#define ES_ejs_web_Cache__origin                                       6
#define ES_ejs_web_Cache_Cache                                         6
#define ES_ejs_web_Cache__initializer__Cache_initializer               7
#define ES_ejs_web_Cache_cache                                         8
#define ES_ejs_web_Cache_read                                          9
#define ES_ejs_web_Cache_write                                         10
#define ES_ejs_web_Cache_remove                                        11
#define ES_ejs_web_Cache_NUM_CLASS_PROP                                12

/**
 * Instance slots for "Cache" type 
 */
#define ES_ejs_web_Cache_NUM_INSTANCE_PROP                             0

/**
 * 
 *    Local slots for methods in type Cache 
 */
#define ES_ejs_web_Cache_Cache_options                                 0
#define ES_ejs_web_Cache_read_domain                                   0
#define ES_ejs_web_Cache_read_key                                      1
#define ES_ejs_web_Cache_write_domain                                  0
#define ES_ejs_web_Cache_write_key                                     1
#define ES_ejs_web_Cache_write_value                                   2
#define ES_ejs_web_Cache_write_options                                 3
#define ES_ejs_web_Cache_remove_domain                                 0
#define ES_ejs_web_Cache_remove_key                                    1


/**
 *   Class property slots for the "Controller" class 
 */
#define ES_ejs_web_Controller__origin                                  6
#define ES_ejs_web_Controller_Controller                               6
#define ES_ejs_web_Controller_ejs_web_initialize                       7
#define ES_ejs_web_Controller_ejs_web_cache                            8
#define ES_ejs_web_Controller_ejs_web_createSession                    9
#define ES_ejs_web_Controller_ejs_web_destroySession                   10
#define ES_ejs_web_Controller_ejs_web_discardOutput                    11
#define ES_ejs_web_Controller_ejs_web_resetFilters                     12
#define ES_ejs_web_Controller_ejs_web_beforeFilter                     13
#define ES_ejs_web_Controller_ejs_web_afterFilter                      14
#define ES_ejs_web_Controller_ejs_web_wrapFilter                       15
#define ES_ejs_web_Controller_runFilters                               16
#define ES_ejs_web_Controller_ejs_web_doAction                         17
#define ES_ejs_web_Controller_ejs_web_sendError                        18
#define ES_ejs_web_Controller_ejs_web_renderError                      19
#define ES_ejs_web_Controller_ejs_web_escapeHtml                       20
#define ES_ejs_web_Controller_ejs_web_html                             21
#define ES_ejs_web_Controller_ejs_web_inform                           22
#define ES_ejs_web_Controller_ejs_web_error                            23
#define ES_ejs_web_Controller_ejs_web_keepAlive                        24
#define ES_ejs_web_Controller_ejs_web_loadView                         25
#define ES_ejs_web_Controller_ejs_web_makeUrl                          26
#define ES_ejs_web_Controller_ejs_web_redirectUrl                      27
#define ES_ejs_web_Controller_ejs_web_redirect                         28
#define ES_ejs_web_Controller_ejs_web_render                           29
#define ES_ejs_web_Controller_ejs_web_renderFile                       30
#define ES_ejs_web_Controller_ejs_web_renderRaw                        31
#define ES_ejs_web_Controller_ejs_web_renderView                       32
#define ES_ejs_web_Controller_reportError                              33
#define ES_ejs_web_Controller_ejs_web_setCookie                        34
#define ES_ejs_web_Controller_ejs_web_setHeader                        35
#define ES_ejs_web_Controller_ejs_web_setHttpCode                      36
#define ES_ejs_web_Controller_ejs_web_setMimeType                      37
#define ES_ejs_web_Controller_ejs_web_unescapeHtml                     38
#define ES_ejs_web_Controller_ejs_web_warn                             39
#define ES_ejs_web_Controller_ejs_web_write                            40
#define ES_ejs_web_Controller_ejs_web_writeHtml                        41
#define ES_ejs_web_Controller_ejs_web_writeRaw                         42
#define ES_ejs_web_Controller_action_missing                           43
#define ES_ejs_web_Controller_NUM_CLASS_PROP                           44

/**
 * Instance slots for "Controller" type 
 */
#define ES_ejs_web_Controller_actionName                               0
#define ES_ejs_web_Controller_originalActionName                       1
#define ES_ejs_web_Controller_absUrl                                   2
#define ES_ejs_web_Controller_appUrl                                   3
#define ES_ejs_web_Controller_controllerName                           4
#define ES_ejs_web_Controller_config                                   5
#define ES_ejs_web_Controller_flash                                    6
#define ES_ejs_web_Controller_home                                     7
#define ES_ejs_web_Controller_host                                     8
#define ES_ejs_web_Controller_params                                   9
#define ES_ejs_web_Controller_request                                  10
#define ES_ejs_web_Controller_response                                 11
#define ES_ejs_web_Controller_session                                  12
#define ES_ejs_web_Controller_isApp                                    13
#define ES_ejs_web_Controller_rendered                                 14
#define ES_ejs_web_Controller_redirected                               15
#define ES_ejs_web_Controller_events                                   16
#define ES_ejs_web_Controller__afterFilters                            17
#define ES_ejs_web_Controller__beforeFilters                           18
#define ES_ejs_web_Controller__wrapFilters                             19
#define ES_ejs_web_Controller_NUM_INSTANCE_PROP                        20

/**
 * 
 *    Local slots for methods in type Controller 
 */
#define ES_ejs_web_Controller_ejs_web_initialize_isApp                 0
#define ES_ejs_web_Controller_ejs_web_initialize_appDir                1
#define ES_ejs_web_Controller_ejs_web_initialize_appUrl                2
#define ES_ejs_web_Controller_ejs_web_initialize_session               3
#define ES_ejs_web_Controller_ejs_web_initialize_host                  4
#define ES_ejs_web_Controller_ejs_web_initialize_request               5
#define ES_ejs_web_Controller_ejs_web_initialize_response              6
#define ES_ejs_web_Controller_ejs_web_initialize_url                   7
#define ES_ejs_web_Controller_ejs_web_initialize_parts                 8
#define ES_ejs_web_Controller_ejs_web_initialize_name                  9
#define ES_ejs_web_Controller_ejs_web_initialize__hoisted_10_adapter   10
#define ES_ejs_web_Controller_ejs_web_initialize__hoisted_11_dbname    11
#define ES_ejs_web_Controller_ejs_web_cache_enable                     0
#define ES_ejs_web_Controller_ejs_web_createSession_timeout            0
#define ES_ejs_web_Controller_ejs_web_beforeFilter_fn                  0
#define ES_ejs_web_Controller_ejs_web_beforeFilter_options             1
#define ES_ejs_web_Controller_ejs_web_afterFilter_fn                   0
#define ES_ejs_web_Controller_ejs_web_afterFilter_options              1
#define ES_ejs_web_Controller_ejs_web_wrapFilter_fn                    0
#define ES_ejs_web_Controller_ejs_web_wrapFilter_options               1
#define ES_ejs_web_Controller_runFilters_filters                       0
#define ES_ejs_web_Controller_runFilters__hoisted_1_filter             1
#define ES_ejs_web_Controller_runFilters__hoisted_2_fn                 2
#define ES_ejs_web_Controller_runFilters__hoisted_3_options            3
#define ES_ejs_web_Controller_ejs_web_doAction_act                     0
#define ES_ejs_web_Controller_ejs_web_doAction_lastFlash               1
#define ES_ejs_web_Controller_ejs_web_doAction__hoisted_2_e            2
#define ES_ejs_web_Controller_ejs_web_doAction__hoisted_3_item         3
#define ES_ejs_web_Controller_ejs_web_doAction__hoisted_4_old          4
#define ES_ejs_web_Controller_ejs_web_sendError_code                   0
#define ES_ejs_web_Controller_ejs_web_sendError_msg                    1
#define ES_ejs_web_Controller_ejs_web_renderError_code                 0
#define ES_ejs_web_Controller_ejs_web_renderError_msg                  1
#define ES_ejs_web_Controller_ejs_web_escapeHtml_s                     0
#define ES_ejs_web_Controller_ejs_web_html_args                        0
#define ES_ejs_web_Controller_ejs_web_html__hoisted_1_s                1
#define ES_ejs_web_Controller_ejs_web_inform_msg                       0
#define ES_ejs_web_Controller_ejs_web_error_msg                        0
#define ES_ejs_web_Controller_ejs_web_keepAlive_on                     0
#define ES_ejs_web_Controller_ejs_web_loadView_path                    0
#define ES_ejs_web_Controller_ejs_web_makeUrl_action                   0
#define ES_ejs_web_Controller_ejs_web_makeUrl_id                       1
#define ES_ejs_web_Controller_ejs_web_makeUrl_options                  2
#define ES_ejs_web_Controller_ejs_web_makeUrl_query                    3
#define ES_ejs_web_Controller_ejs_web_makeUrl_url                      4
#define ES_ejs_web_Controller_ejs_web_makeUrl__hoisted_5_cname         5
#define ES_ejs_web_Controller_ejs_web_redirectUrl_url                  0
#define ES_ejs_web_Controller_ejs_web_redirectUrl_code                 1
#define ES_ejs_web_Controller_ejs_web_redirect_action                  0
#define ES_ejs_web_Controller_ejs_web_redirect_id                      1
#define ES_ejs_web_Controller_ejs_web_redirect_options                 2
#define ES_ejs_web_Controller_ejs_web_render_args                      0
#define ES_ejs_web_Controller_ejs_web_renderFile_filename              0
#define ES_ejs_web_Controller_ejs_web_renderFile_file                  1
#define ES_ejs_web_Controller_ejs_web_renderFile__hoisted_2_e          2
#define ES_ejs_web_Controller_ejs_web_renderRaw_args                   0
#define ES_ejs_web_Controller_ejs_web_renderView_viewName              0
#define ES_ejs_web_Controller_ejs_web_renderView__hoisted_1_name       1
#define ES_ejs_web_Controller_ejs_web_renderView__hoisted_2_viewClass  2
#define ES_ejs_web_Controller_ejs_web_renderView__hoisted_3_e          3
#define ES_ejs_web_Controller_ejs_web_renderView__hoisted_4_n          4
#define ES_ejs_web_Controller_ejs_web_renderView__hoisted_5_e          5
#define ES_ejs_web_Controller_ejs_web_renderView__hoisted_6_msg        6
#define ES_ejs_web_Controller_reportError_code                         0
#define ES_ejs_web_Controller_reportError_msg                          1
#define ES_ejs_web_Controller_reportError_e                            2
#define ES_ejs_web_Controller_ejs_web_setCookie_name                   0
#define ES_ejs_web_Controller_ejs_web_setCookie_value                  1
#define ES_ejs_web_Controller_ejs_web_setCookie_path                   2
#define ES_ejs_web_Controller_ejs_web_setCookie_domain                 3
#define ES_ejs_web_Controller_ejs_web_setCookie_lifetime               4
#define ES_ejs_web_Controller_ejs_web_setCookie_secure                 5
#define ES_ejs_web_Controller_ejs_web_setHeader_key                    0
#define ES_ejs_web_Controller_ejs_web_setHeader_value                  1
#define ES_ejs_web_Controller_ejs_web_setHeader_allowMultiple          2
#define ES_ejs_web_Controller_ejs_web_setHttpCode_code                 0
#define ES_ejs_web_Controller_ejs_web_setMimeType_format               0
#define ES_ejs_web_Controller_ejs_web_unescapeHtml_s                   0
#define ES_ejs_web_Controller_ejs_web_warn_msg                         0
#define ES_ejs_web_Controller_ejs_web_write_args                       0
#define ES_ejs_web_Controller_ejs_web_writeHtml_args                   0
#define ES_ejs_web_Controller_ejs_web_writeRaw_args                    0


/**
 *   Class property slots for the "_SoloController" class 
 */
#define ES_ejs_web__SoloController__origin                             44
#define ES_ejs_web__SoloController__SoloController                     44
#define ES_ejs_web__SoloController_NUM_CLASS_PROP                      45

/**
 * Instance slots for "_SoloController" type 
 */
#define ES_ejs_web__SoloController_NUM_INSTANCE_PROP                   20


/**
 *   Class property slots for the "Cookie" class 
 */
#define ES_ejs_web_Cookie__origin                                      6
#define ES_ejs_web_Cookie_Cookie                                       6
#define ES_ejs_web_Cookie_NUM_CLASS_PROP                               7

/**
 * Instance slots for "Cookie" type 
 */
#define ES_ejs_web_Cookie_name                                         0
#define ES_ejs_web_Cookie_value                                        1
#define ES_ejs_web_Cookie_domain                                       2
#define ES_ejs_web_Cookie_path                                         3
#define ES_ejs_web_Cookie_NUM_INSTANCE_PROP                            4


/**
 *   Class property slots for the "Host" class 
 */
#define ES_ejs_web_Host__origin                                        6
#define ES_ejs_web_Host_Host                                           6
#define ES_ejs_web_Host_NUM_CLASS_PROP                                 7

/**
 * Instance slots for "Host" type 
 */
#define ES_ejs_web_Host_documentRoot                                   0
#define ES_ejs_web_Host_name                                           1
#define ES_ejs_web_Host_protocol                                       2
#define ES_ejs_web_Host_isVirtualHost                                  3
#define ES_ejs_web_Host_isNamedVirtualHost                             4
#define ES_ejs_web_Host_software                                       5
#define ES_ejs_web_Host_logErrors                                      6
#define ES_ejs_web_Host_NUM_INSTANCE_PROP                              7


/**
 *   Class property slots for the "Request" class 
 */
#define ES_ejs_web_Request__origin                                     6
#define ES_ejs_web_Request_Request                                     6
#define ES_ejs_web_Request_NUM_CLASS_PROP                              7

/**
 * Instance slots for "Request" type 
 */
#define ES_ejs_web_Request_accept                                      0
#define ES_ejs_web_Request_acceptCharset                               1
#define ES_ejs_web_Request_acceptEncoding                              2
#define ES_ejs_web_Request_authAcl                                     3
#define ES_ejs_web_Request_authGroup                                   4
#define ES_ejs_web_Request_authType                                    5
#define ES_ejs_web_Request_authUser                                    6
#define ES_ejs_web_Request_body                                        7
#define ES_ejs_web_Request_connection                                  8
#define ES_ejs_web_Request_contentLength                               9
#define ES_ejs_web_Request_cookies                                     10
#define ES_ejs_web_Request_extension                                   11
#define ES_ejs_web_Request_files                                       12
#define ES_ejs_web_Request_headers                                     13
#define ES_ejs_web_Request_hostName                                    14
#define ES_ejs_web_Request_method                                      15
#define ES_ejs_web_Request_mimeType                                    16
#define ES_ejs_web_Request_pathInfo                                    17
#define ES_ejs_web_Request_pathTranslated                              18
#define ES_ejs_web_Request_pragma                                      19
#define ES_ejs_web_Request_query                                       20
#define ES_ejs_web_Request_originalUri                                 21
#define ES_ejs_web_Request_referrer                                    22
#define ES_ejs_web_Request_remoteAddress                               23
#define ES_ejs_web_Request_remoteHost                                  24
#define ES_ejs_web_Request_sessionID                                   25
#define ES_ejs_web_Request_url                                         26
#define ES_ejs_web_Request_userAgent                                   27
#define ES_ejs_web_Request_NUM_INSTANCE_PROP                           28


/**
 *   Class property slots for the "Response" class 
 */
#define ES_ejs_web_Response__origin                                    6
#define ES_ejs_web_Response_Response                                   6
#define ES_ejs_web_Response_NUM_CLASS_PROP                             7

/**
 * Instance slots for "Response" type 
 */
#define ES_ejs_web_Response_code                                       0
#define ES_ejs_web_Response_filename                                   1
#define ES_ejs_web_Response_headers                                    2
#define ES_ejs_web_Response_mimeType                                   3
#define ES_ejs_web_Response_NUM_INSTANCE_PROP                          4


/**
 *   Class property slots for the "Session" class 
 */
#define ES_ejs_web_Session__origin                                     6
#define ES_ejs_web_Session_NUM_CLASS_PROP                              6

/**
 * Instance slots for "Session" type 
 */
#define ES_ejs_web_Session_NUM_INSTANCE_PROP                           0


/**
 *   Class property slots for the "UploadFile" class 
 */
#define ES_ejs_web_UploadFile__origin                                  6
#define ES_ejs_web_UploadFile_UploadFile                               6
#define ES_ejs_web_UploadFile_NUM_CLASS_PROP                           7

/**
 * Instance slots for "UploadFile" type 
 */
#define ES_ejs_web_UploadFile_clientFilename                           0
#define ES_ejs_web_UploadFile_contentType                              1
#define ES_ejs_web_UploadFile_filename                                 2
#define ES_ejs_web_UploadFile_name                                     3
#define ES_ejs_web_UploadFile_size                                     4
#define ES_ejs_web_UploadFile_NUM_INSTANCE_PROP                        5


/**
 *   Class property slots for the "View" class 
 */
#define ES_ejs_web_View__origin                                        6
#define ES_ejs_web_View_View                                           6
#define ES_ejs_web_View__initializer__View_initializer                 7
#define ES_ejs_web_View_ejs_web_getNextId                              8
#define ES_ejs_web_View_render                                         9
#define ES_ejs_web_View_ejs_web_aform                                  10
#define ES_ejs_web_View_ejs_web_alink                                  11
#define ES_ejs_web_View_ejs_web_button                                 12
#define ES_ejs_web_View_ejs_web_buttonLink                             13
#define ES_ejs_web_View_ejs_web_chart                                  14
#define ES_ejs_web_View_ejs_web_checkbox                               15
#define ES_ejs_web_View_ejs_web_endform                                16
#define ES_ejs_web_View_ejs_web_form                                   17
#define ES_ejs_web_View_ejs_web_image                                  18
#define ES_ejs_web_View_ejs_web_imageLink                              19
#define ES_ejs_web_View_ejs_web_input                                  20
#define ES_ejs_web_View_ejs_web_label                                  21
#define ES_ejs_web_View_ejs_web_link                                   22
#define ES_ejs_web_View_ejs_web_extlink                                23
#define ES_ejs_web_View_ejs_web_list                                   24
#define ES_ejs_web_View_ejs_web_mail                                   25
#define ES_ejs_web_View_ejs_web_progress                               26
#define ES_ejs_web_View_ejs_web_radio                                  27
#define ES_ejs_web_View_ejs_web_script                                 28
#define ES_ejs_web_View_ejs_web_status                                 29
#define ES_ejs_web_View_ejs_web_stylesheet                             30
#define ES_ejs_web_View_ejs_web_table                                  31
#define ES_ejs_web_View_ejs_web_tabs                                   32
#define ES_ejs_web_View_ejs_web_text                                   33
#define ES_ejs_web_View_ejs_web_textarea                               34
#define ES_ejs_web_View_ejs_web_tree                                   35
#define ES_ejs_web_View_ejs_web_flash                                  36
#define ES_ejs_web_View_formErrors                                     37
#define ES_ejs_web_View_ejs_web_createSession                          38
#define ES_ejs_web_View_ejs_web_destroySession                         39
#define ES_ejs_web_View_ejs_web_html                                   40
#define ES_ejs_web_View_ejs_web_makeUrl                                41
#define ES_ejs_web_View_ejs_web_redirectUrl                            42
#define ES_ejs_web_View_ejs_web_redirect                               43
#define ES_ejs_web_View_ejs_web_setCookie                              44
#define ES_ejs_web_View_ejs_web_setHeader                              45
#define ES_ejs_web_View_ejs_web_setHttpCode                            46
#define ES_ejs_web_View_ejs_web_setMimeType                            47
#define ES_ejs_web_View_ejs_web_write                                  48
#define ES_ejs_web_View_ejs_web_writeHtml                              49
#define ES_ejs_web_View_ejs_web_writeRaw                               50
#define ES_ejs_web_View_ejs_web_d                                      51
#define ES_ejs_web_View_addHelper                                      52
#define ES_ejs_web_View_getConnector                                   53
#define ES_ejs_web_View_setOptions                                     54
#define ES_ejs_web_View_ejs_web_getValue                               55
#define ES_ejs_web_View_ejs_web_date                                   56
#define ES_ejs_web_View_ejs_web_currency                               57
#define ES_ejs_web_View_ejs_web_number                                 58
#define ES_ejs_web_View_htmlOptions                                    59
#define ES_ejs_web_View_ejs_web_getOptions                             60
#define ES_ejs_web_View_pivot                                          61
#define ES_ejs_web_View_filter                                         62
#define ES_ejs_web_View_NUM_CLASS_PROP                                 63

/**
 * Instance slots for "View" type 
 */
#define ES_ejs_web_View_ejs_web_controller                             0
#define ES_ejs_web_View_currentModel                                   1
#define ES_ejs_web_View_config                                         2
#define ES_ejs_web_View_nextId                                         3
#define ES_ejs_web_View_NUM_INSTANCE_PROP                              4

/**
 * 
 *    Local slots for methods in type View 
 */
#define ES_ejs_web_View_View_controller                                0
#define ES_ejs_web_View_ejs_web_aform_action                           0
#define ES_ejs_web_View_ejs_web_aform_record                           1
#define ES_ejs_web_View_ejs_web_aform_options                          2
#define ES_ejs_web_View_ejs_web_aform_connector                        3
#define ES_ejs_web_View_ejs_web_alink_text                             0
#define ES_ejs_web_View_ejs_web_alink_action                           1
#define ES_ejs_web_View_ejs_web_alink_options                          2
#define ES_ejs_web_View_ejs_web_alink_connector                        3
#define ES_ejs_web_View_ejs_web_button_value                           0
#define ES_ejs_web_View_ejs_web_button_buttonName                      1
#define ES_ejs_web_View_ejs_web_button_options                         2
#define ES_ejs_web_View_ejs_web_button_connector                       3
#define ES_ejs_web_View_ejs_web_buttonLink_text                        0
#define ES_ejs_web_View_ejs_web_buttonLink_action                      1
#define ES_ejs_web_View_ejs_web_buttonLink_options                     2
#define ES_ejs_web_View_ejs_web_buttonLink_connector                   3
#define ES_ejs_web_View_ejs_web_chart_initialData                      0
#define ES_ejs_web_View_ejs_web_chart_options                          1
#define ES_ejs_web_View_ejs_web_chart_connector                        2
#define ES_ejs_web_View_ejs_web_checkbox_field                         0
#define ES_ejs_web_View_ejs_web_checkbox_choice                        1
#define ES_ejs_web_View_ejs_web_checkbox_options                       2
#define ES_ejs_web_View_ejs_web_checkbox_value                         3
#define ES_ejs_web_View_ejs_web_checkbox_connector                     4
#define ES_ejs_web_View_ejs_web_endform_connector                      0
#define ES_ejs_web_View_ejs_web_form_action                            0
#define ES_ejs_web_View_ejs_web_form_record                            1
#define ES_ejs_web_View_ejs_web_form_options                           2
#define ES_ejs_web_View_ejs_web_form_connector                         3
#define ES_ejs_web_View_ejs_web_image_src                              0
#define ES_ejs_web_View_ejs_web_image_options                          1
#define ES_ejs_web_View_ejs_web_image_connector                        2
#define ES_ejs_web_View_ejs_web_imageLink_image                        0
#define ES_ejs_web_View_ejs_web_imageLink_action                       1
#define ES_ejs_web_View_ejs_web_imageLink_options                      2
#define ES_ejs_web_View_ejs_web_imageLink_connector                    3
#define ES_ejs_web_View_ejs_web_input_field                            0
#define ES_ejs_web_View_ejs_web_input_options                          1
#define ES_ejs_web_View_ejs_web_label_text                             0
#define ES_ejs_web_View_ejs_web_label_options                          1
#define ES_ejs_web_View_ejs_web_label_connector                        2
#define ES_ejs_web_View_ejs_web_link_text                              0
#define ES_ejs_web_View_ejs_web_link_action                            1
#define ES_ejs_web_View_ejs_web_link_options                           2
#define ES_ejs_web_View_ejs_web_link_connector                         3
#define ES_ejs_web_View_ejs_web_extlink_text                           0
#define ES_ejs_web_View_ejs_web_extlink_url                            1
#define ES_ejs_web_View_ejs_web_extlink_options                        2
#define ES_ejs_web_View_ejs_web_extlink_connector                      3
#define ES_ejs_web_View_ejs_web_list_field                             0
#define ES_ejs_web_View_ejs_web_list_choices                           1
#define ES_ejs_web_View_ejs_web_list_options                           2
#define ES_ejs_web_View_ejs_web_list_value                             3
#define ES_ejs_web_View_ejs_web_list_connector                         4
#define ES_ejs_web_View_ejs_web_mail_nameText                          0
#define ES_ejs_web_View_ejs_web_mail_address                           1
#define ES_ejs_web_View_ejs_web_mail_options                           2
#define ES_ejs_web_View_ejs_web_mail_connector                         3
#define ES_ejs_web_View_ejs_web_progress_initialData                   0
#define ES_ejs_web_View_ejs_web_progress_options                       1
#define ES_ejs_web_View_ejs_web_progress_connector                     2
#define ES_ejs_web_View_ejs_web_radio_field                            0
#define ES_ejs_web_View_ejs_web_radio_choices                          1
#define ES_ejs_web_View_ejs_web_radio_options                          2
#define ES_ejs_web_View_ejs_web_radio_value                            3
#define ES_ejs_web_View_ejs_web_radio_connector                        4
#define ES_ejs_web_View_ejs_web_script_url                             0
#define ES_ejs_web_View_ejs_web_script_options                         1
#define ES_ejs_web_View_ejs_web_script_connector                       2
#define ES_ejs_web_View_ejs_web_script__hoisted_3_u                    3
#define ES_ejs_web_View_ejs_web_status_initialData                     0
#define ES_ejs_web_View_ejs_web_status_options                         1
#define ES_ejs_web_View_ejs_web_status_connector                       2
#define ES_ejs_web_View_ejs_web_stylesheet_url                         0
#define ES_ejs_web_View_ejs_web_stylesheet_options                     1
#define ES_ejs_web_View_ejs_web_stylesheet_connector                   2
#define ES_ejs_web_View_ejs_web_stylesheet__hoisted_3_u                3
#define ES_ejs_web_View_ejs_web_table_data                             0
#define ES_ejs_web_View_ejs_web_table_options                          1
#define ES_ejs_web_View_ejs_web_table_connector                        2
#define ES_ejs_web_View_ejs_web_tabs_initialData                       0
#define ES_ejs_web_View_ejs_web_tabs_options                           1
#define ES_ejs_web_View_ejs_web_tabs_connector                         2
#define ES_ejs_web_View_ejs_web_text_field                             0
#define ES_ejs_web_View_ejs_web_text_options                           1
#define ES_ejs_web_View_ejs_web_text_value                             2
#define ES_ejs_web_View_ejs_web_text_connector                         3
#define ES_ejs_web_View_ejs_web_textarea_field                         0
#define ES_ejs_web_View_ejs_web_textarea_options                       1
#define ES_ejs_web_View_ejs_web_textarea_value                         2
#define ES_ejs_web_View_ejs_web_textarea_connector                     3
#define ES_ejs_web_View_ejs_web_tree_initialData                       0
#define ES_ejs_web_View_ejs_web_tree_options                           1
#define ES_ejs_web_View_ejs_web_tree_connector                         2
#define ES_ejs_web_View_ejs_web_flash_kinds                            0
#define ES_ejs_web_View_ejs_web_flash_options                          1
#define ES_ejs_web_View_ejs_web_flash_cflash                           2
#define ES_ejs_web_View_ejs_web_flash_msgs                             3
#define ES_ejs_web_View_ejs_web_flash__hoisted_4_kind                  4
#define ES_ejs_web_View_ejs_web_flash__hoisted_5_kind                  5
#define ES_ejs_web_View_ejs_web_flash__hoisted_6_msg                   6
#define ES_ejs_web_View_ejs_web_flash__hoisted_7_connector             7
#define ES_ejs_web_View_formErrors_model                               0
#define ES_ejs_web_View_formErrors_errors                              1
#define ES_ejs_web_View_formErrors__hoisted_2_e                        2
#define ES_ejs_web_View_ejs_web_createSession_timeout                  0
#define ES_ejs_web_View_ejs_web_html_args                              0
#define ES_ejs_web_View_ejs_web_makeUrl_action                         0
#define ES_ejs_web_View_ejs_web_makeUrl_id                             1
#define ES_ejs_web_View_ejs_web_makeUrl_options                        2
#define ES_ejs_web_View_ejs_web_redirectUrl_url                        0
#define ES_ejs_web_View_ejs_web_redirectUrl_code                       1
#define ES_ejs_web_View_ejs_web_redirect_action                        0
#define ES_ejs_web_View_ejs_web_redirect_id                            1
#define ES_ejs_web_View_ejs_web_redirect_options                       2
#define ES_ejs_web_View_ejs_web_setCookie_name                         0
#define ES_ejs_web_View_ejs_web_setCookie_value                        1
#define ES_ejs_web_View_ejs_web_setCookie_lifetime                     2
#define ES_ejs_web_View_ejs_web_setCookie_path                         3
#define ES_ejs_web_View_ejs_web_setCookie_secure                       4
#define ES_ejs_web_View_ejs_web_setHeader_key                          0
#define ES_ejs_web_View_ejs_web_setHeader_value                        1
#define ES_ejs_web_View_ejs_web_setHeader_allowMultiple                2
#define ES_ejs_web_View_ejs_web_setHttpCode_code                       0
#define ES_ejs_web_View_ejs_web_setMimeType_format                     0
#define ES_ejs_web_View_ejs_web_write_args                             0
#define ES_ejs_web_View_ejs_web_writeHtml_args                         0
#define ES_ejs_web_View_ejs_web_writeRaw_args                          0
#define ES_ejs_web_View_ejs_web_d_args                                 0
#define ES_ejs_web_View_ejs_web_d_e                                    1
#define ES_ejs_web_View_addHelper_fun                                  0
#define ES_ejs_web_View_addHelper_overwrite                            1
#define ES_ejs_web_View_addHelper_name                                 2
#define ES_ejs_web_View_getConnector_kind                              0
#define ES_ejs_web_View_getConnector_options                           1
#define ES_ejs_web_View_getConnector_connectorName                     2
#define ES_ejs_web_View_getConnector_name                              3
#define ES_ejs_web_View_getConnector__hoisted_4_e                      4
#define ES_ejs_web_View_setOptions_field                               0
#define ES_ejs_web_View_setOptions_options                             1
#define ES_ejs_web_View_ejs_web_getValue_model                         0
#define ES_ejs_web_View_ejs_web_getValue_field                         1
#define ES_ejs_web_View_ejs_web_getValue_options                       2
#define ES_ejs_web_View_ejs_web_getValue_value                         3
#define ES_ejs_web_View_ejs_web_getValue_typeName                      4
#define ES_ejs_web_View_ejs_web_getValue_fmt                           5
#define ES_ejs_web_View_ejs_web_getValue__hoisted_6_part               6
#define ES_ejs_web_View_ejs_web_date_fmt                               0
#define ES_ejs_web_View_ejs_web_date___fun_5437__                      1
#define ES_ejs_web_View_ejs_web_currency_fmt                           0
#define ES_ejs_web_View_ejs_web_currency___fun_5471__                  1
#define ES_ejs_web_View_ejs_web_number_fmt                             0
#define ES_ejs_web_View_ejs_web_number___fun_5501__                    1
#define ES_ejs_web_View_ejs_web_getOptions_options                     0
#define ES_ejs_web_View_ejs_web_getOptions_result                      1
#define ES_ejs_web_View_ejs_web_getOptions__hoisted_2_option           2
#define ES_ejs_web_View_ejs_web_getOptions__hoisted_3_mapped           3
#define ES_ejs_web_View_pivot_grid                                     0
#define ES_ejs_web_View_pivot_options                                  1
#define ES_ejs_web_View_pivot_headers                                  2
#define ES_ejs_web_View_pivot_i                                        3
#define ES_ejs_web_View_pivot_table                                    4
#define ES_ejs_web_View_pivot_row                                      5
#define ES_ejs_web_View_pivot__hoisted_6_name                          6
#define ES_ejs_web_View_pivot__hoisted_7_name                          7
#define ES_ejs_web_View_pivot__hoisted_8_r                             8
#define ES_ejs_web_View_filter_data                                    0
#define ES_ejs_web_View_filter__hoisted_1_i                            1
#define ES_ejs_web_View_filter__hoisted_2_found                        2
#define ES_ejs_web_View_filter__hoisted_3_f                            3


/**
 *   Class property slots for the "LocalModel" class 
 */
#define ES_LocalModel__origin                                          6
#define ES_LocalModel_Record                                           6
#define ES_LocalModel__initializer__Record_initializer                 7
#define ES_LocalModel_ejs_db_int__assocName                            8
#define ES_LocalModel_ejs_db_int__belongsTo                            9
#define ES_LocalModel_ejs_db_int__className                            10
#define ES_LocalModel_ejs_db_int__columns                              11
#define ES_LocalModel_ejs_db_int__hasOne                               12
#define ES_LocalModel_ejs_db_int__hasMany                              13
#define ES_LocalModel_ejs_db_int__db                                   14
#define ES_LocalModel_ejs_db_int__foreignId                            15
#define ES_LocalModel_ejs_db_int__keyName                              16
#define ES_LocalModel_ejs_db_int__tableName                            17
#define ES_LocalModel_ejs_db_int__trace                                18
#define ES_LocalModel_ejs_db_int__validations                          19
#define ES_LocalModel_ejs_db_int__beforeFilters                        20
#define ES_LocalModel_ejs_db_int__afterFilters                         21
#define ES_LocalModel_ejs_db_int__wrapFilters                          22
#define ES_LocalModel_ejs_db_ErrorMessages                             23
#define ES_LocalModel_ejs_db_initialize                                24
#define ES_LocalModel_ejs_db_afterFilter                               25
#define ES_LocalModel_ejs_db_beforeFilter                              26
#define ES_LocalModel_ejs_db_belongsTo                                 27
#define ES_LocalModel_cachedRead                                       28
#define ES_LocalModel_checkFormat                                      29
#define ES_LocalModel_checkNumber                                      30
#define ES_LocalModel_checkPresent                                     31
#define ES_LocalModel_checkUnique                                      32
#define ES_LocalModel_coerceToEjsTypes                                 33
#define ES_LocalModel_createAssociations                               34
#define ES_LocalModel_createRecord                                     35
#define ES_LocalModel_ejs_db_error                                     36
#define ES_LocalModel_ejs_db_find                                      37
#define ES_LocalModel_ejs_db_findAll                                   38
#define ES_LocalModel_ejs_db_findOneWhere                              39
#define ES_LocalModel_ejs_db_findWhere                                 40
#define ES_LocalModel_ejs_db_getColumnNames                            41
#define ES_LocalModel_ejs_db_getColumnTitles                           42
#define ES_LocalModel_ejs_db_getColumnType                             43
#define ES_LocalModel_ejs_db_getDb                                     44
#define ES_LocalModel_ejs_db_getErrors                                 45
#define ES_LocalModel_ejs_db_getKeyName                                46
#define ES_LocalModel_ejs_db_getNumRows                                47
#define ES_LocalModel_getSchema                                        48
#define ES_LocalModel_ejs_db_getTableName                              49
#define ES_LocalModel_ejs_db_hasAndBelongsToMany                       50
#define ES_LocalModel_ejs_db_hasError                                  51
#define ES_LocalModel_ejs_db_hasMany                                   52
#define ES_LocalModel_ejs_db_hasOne                                    53
#define ES_LocalModel_innerFind                                        54
#define ES_LocalModel_makeLazyReader                                   55
#define ES_LocalModel_mapSqlTypeToEjs                                  56
#define ES_LocalModel_prepareValue                                     57
#define ES_LocalModel_readRecords                                      58
#define ES_LocalModel_ejs_db_remove                                    59
#define ES_LocalModel_runFilters                                       60
#define ES_LocalModel_ejs_db_save                                      61
#define ES_LocalModel_ejs_db_saveUpdate                                62
#define ES_LocalModel_ejs_db_setDb                                     63
#define ES_LocalModel_ejs_db_setKeyName                                64
#define ES_LocalModel_ejs_db_setTableName                              65
#define ES_LocalModel_ejs_db_sql                                       66
#define ES_LocalModel_ejs_db_trace                                     67
#define ES_LocalModel_ejs_db_validateFormat                            68
#define ES_LocalModel_ejs_db_validateNumber                            69
#define ES_LocalModel_ejs_db_validatePresence                          70
#define ES_LocalModel_ejs_db_validateRecord                            71
#define ES_LocalModel_ejs_db_validateUnique                            72
#define ES_LocalModel_ejs_db_wrapFilter                                73
#define ES_LocalModel_ejs_db_columnNames                               74
#define ES_LocalModel_ejs_db_columnTitles                              75
#define ES_LocalModel_ejs_db_db                                        76
#define ES_LocalModel_ejs_db_keyName                                   77
#define ES_LocalModel_ejs_db_numRows                                   78
#define ES_LocalModel_ejs_db_tableName                                 79
#define ES_LocalModel_ejs_db_constructor                               80
#define ES_LocalModel_LocalModel                                       81
#define ES_LocalModel__initializer__LocalModel_initializer             82
#define ES_LocalModel_NUM_CLASS_PROP                                   83

/**
 * Instance slots for "LocalModel" type 
 */
#define ES_LocalModel_ejs_db_int__keyValue                             0
#define ES_LocalModel_ejs_db_int__errors                               1
#define ES_LocalModel_ejs_db_int__cacheAssoc                           2
#define ES_LocalModel_NUM_INSTANCE_PROP                                3

/**
 * 
 *    Local slots for methods in type LocalModel 
 */
#define ES_LocalModel_Record_fields                                    0
#define ES_LocalModel_ejs_db_initialize_fields                         0
#define ES_LocalModel_ejs_db_initialize__hoisted_1_field               1
#define ES_LocalModel_ejs_db_afterFilter_fn                            0
#define ES_LocalModel_ejs_db_afterFilter_options                       1
#define ES_LocalModel_ejs_db_beforeFilter_fn                           0
#define ES_LocalModel_ejs_db_beforeFilter_options                      1
#define ES_LocalModel_ejs_db_belongsTo_owner                           0
#define ES_LocalModel_ejs_db_belongsTo_options                         1
#define ES_LocalModel_cachedRead_rec                                   0
#define ES_LocalModel_cachedRead_field                                 1
#define ES_LocalModel_cachedRead_model                                 2
#define ES_LocalModel_cachedRead_key                                   3
#define ES_LocalModel_cachedRead_options                               4
#define ES_LocalModel_checkFormat_thisObj                              0
#define ES_LocalModel_checkFormat_field                                1
#define ES_LocalModel_checkFormat_value                                2
#define ES_LocalModel_checkFormat_options                              3
#define ES_LocalModel_checkNumber_thisObj                              0
#define ES_LocalModel_checkNumber_field                                1
#define ES_LocalModel_checkNumber_value                                2
#define ES_LocalModel_checkNumber_options                              3
#define ES_LocalModel_checkPresent_thisObj                             0
#define ES_LocalModel_checkPresent_field                               1
#define ES_LocalModel_checkPresent_value                               2
#define ES_LocalModel_checkPresent_options                             3
#define ES_LocalModel_checkUnique_thisObj                              0
#define ES_LocalModel_checkUnique_field                                1
#define ES_LocalModel_checkUnique_value                                2
#define ES_LocalModel_checkUnique_options                              3
#define ES_LocalModel_checkUnique_grid                                 4
#define ES_LocalModel_coerceToEjsTypes__hoisted_0_field                0
#define ES_LocalModel_coerceToEjsTypes__hoisted_1_col                  1
#define ES_LocalModel_coerceToEjsTypes__hoisted_2_value                2
#define ES_LocalModel_createAssociations_rec                           0
#define ES_LocalModel_createAssociations_set                           1
#define ES_LocalModel_createAssociations_preload                       2
#define ES_LocalModel_createAssociations_options                       3
#define ES_LocalModel_createAssociations__hoisted_4_model              4
#define ES_LocalModel_createAssociations__hoisted_5_association        5
#define ES_LocalModel_createAssociations__hoisted_6_field              6
#define ES_LocalModel_createAssociations__hoisted_7_f                  7
#define ES_LocalModel_createAssociations__hoisted_8_field              8
#define ES_LocalModel_createAssociations__hoisted_9_f                  9
#define ES_LocalModel_createRecord_data                                0
#define ES_LocalModel_createRecord_options                             1
#define ES_LocalModel_createRecord_rec                                 2
#define ES_LocalModel_createRecord_subOptions                          3
#define ES_LocalModel_createRecord__hoisted_4_model                    4
#define ES_LocalModel_createRecord__hoisted_5_model                    5
#define ES_LocalModel_ejs_db_error_field                               0
#define ES_LocalModel_ejs_db_error_msg                                 1
#define ES_LocalModel_ejs_db_find_key                                  0
#define ES_LocalModel_ejs_db_find_options                              1
#define ES_LocalModel_ejs_db_find_grid                                 2
#define ES_LocalModel_ejs_db_find__hoisted_3_results                   3
#define ES_LocalModel_ejs_db_findAll_options                           0
#define ES_LocalModel_ejs_db_findAll_grid                              1
#define ES_LocalModel_ejs_db_findAll__hoisted_2_i                      2
#define ES_LocalModel_ejs_db_findOneWhere_where                        0
#define ES_LocalModel_ejs_db_findOneWhere_grid                         1
#define ES_LocalModel_ejs_db_findWhere_where                           0
#define ES_LocalModel_ejs_db_findWhere_count                           1
#define ES_LocalModel_ejs_db_findWhere_grid                            2
#define ES_LocalModel_ejs_db_findWhere__hoisted_3_i                    3
#define ES_LocalModel_ejs_db_getColumnNames_result                     0
#define ES_LocalModel_ejs_db_getColumnNames__hoisted_1_col             1
#define ES_LocalModel_ejs_db_getColumnTitles_result                    0
#define ES_LocalModel_ejs_db_getColumnTitles__hoisted_1_col            1
#define ES_LocalModel_ejs_db_getColumnType_field                       0
#define ES_LocalModel_ejs_db_getNumRows_cmd                            0
#define ES_LocalModel_ejs_db_getNumRows_grid                           1
#define ES_LocalModel_getSchema_sql                                    0
#define ES_LocalModel_getSchema_grid                                   1
#define ES_LocalModel_getSchema__hoisted_2_row                         2
#define ES_LocalModel_getSchema__hoisted_3_name                        3
#define ES_LocalModel_getSchema__hoisted_4_sqlType                     4
#define ES_LocalModel_getSchema__hoisted_5_ejsType                     5
#define ES_LocalModel_ejs_db_hasAndBelongsToMany_model                 0
#define ES_LocalModel_ejs_db_hasAndBelongsToMany_options               1
#define ES_LocalModel_ejs_db_hasError_field                            0
#define ES_LocalModel_ejs_db_hasMany_model                             0
#define ES_LocalModel_ejs_db_hasMany_options                           1
#define ES_LocalModel_ejs_db_hasOne_model                              0
#define ES_LocalModel_ejs_db_hasOne_options                            1
#define ES_LocalModel_innerFind_key                                    0
#define ES_LocalModel_innerFind_limit                                  1
#define ES_LocalModel_innerFind_options                                2
#define ES_LocalModel_innerFind_cmd                                    3
#define ES_LocalModel_innerFind_columns                                4
#define ES_LocalModel_innerFind_from                                   5
#define ES_LocalModel_innerFind_conditions                             6
#define ES_LocalModel_innerFind_where                                  7
#define ES_LocalModel_innerFind_results                                8
#define ES_LocalModel_innerFind__hoisted_9_index                       9
#define ES_LocalModel_innerFind__hoisted_10_model                      10
#define ES_LocalModel_innerFind__hoisted_11_entry                      11
#define ES_LocalModel_innerFind__hoisted_12_owner                      12
#define ES_LocalModel_innerFind__hoisted_13_owner                      13
#define ES_LocalModel_innerFind__hoisted_14_tname                      14
#define ES_LocalModel_innerFind__hoisted_15_parts                      15
#define ES_LocalModel_innerFind__hoisted_16_whereConditions            16
#define ES_LocalModel_innerFind__hoisted_17_cond                       17
#define ES_LocalModel_innerFind__hoisted_18_field                      18
#define ES_LocalModel_innerFind__hoisted_19_e                          19
#define ES_LocalModel_makeLazyReader_rec                               0
#define ES_LocalModel_makeLazyReader_field                             1
#define ES_LocalModel_makeLazyReader_model                             2
#define ES_LocalModel_makeLazyReader_key                               3
#define ES_LocalModel_makeLazyReader_options                           4
#define ES_LocalModel_makeLazyReader___fun_3930__                      5
#define ES_LocalModel_makeLazyReader_lazyReader                        6
#define ES_LocalModel_mapSqlTypeToEjs_sqlType                          0
#define ES_LocalModel_mapSqlTypeToEjs_ejsType                          1
#define ES_LocalModel_prepareValue_field                               0
#define ES_LocalModel_prepareValue_value                               1
#define ES_LocalModel_prepareValue_col                                 2
#define ES_LocalModel_readRecords_key                                  0
#define ES_LocalModel_readRecords_options                              1
#define ES_LocalModel_readRecords_data                                 2
#define ES_LocalModel_readRecords__hoisted_3_result                    3
#define ES_LocalModel_readRecords__hoisted_4_row                       4
#define ES_LocalModel_ejs_db_remove_keys                               0
#define ES_LocalModel_ejs_db_remove__hoisted_1_key                     1
#define ES_LocalModel_ejs_db_remove__hoisted_2_cmd                     2
#define ES_LocalModel_runFilters_filters                               0
#define ES_LocalModel_runFilters__hoisted_1_filter                     1
#define ES_LocalModel_runFilters__hoisted_2_fn                         2
#define ES_LocalModel_runFilters__hoisted_3_options                    3
#define ES_LocalModel_runFilters__hoisted_4_only                       4
#define ES_LocalModel_ejs_db_save_sql                                  0
#define ES_LocalModel_ejs_db_save_result                               1
#define ES_LocalModel_ejs_db_save__hoisted_2_field                     2
#define ES_LocalModel_ejs_db_save__hoisted_3_field                     3
#define ES_LocalModel_ejs_db_save__hoisted_4_field                     4
#define ES_LocalModel_ejs_db_saveUpdate_fields                         0
#define ES_LocalModel_ejs_db_saveUpdate__hoisted_1_field               1
#define ES_LocalModel_ejs_db_setDb_database                            0
#define ES_LocalModel_ejs_db_setKeyName_name                           0
#define ES_LocalModel_ejs_db_setTableName_name                         0
#define ES_LocalModel_ejs_db_sql_cmd                                   0
#define ES_LocalModel_ejs_db_sql_count                                 1
#define ES_LocalModel_ejs_db_trace_on                                  0
#define ES_LocalModel_ejs_db_validateFormat_fields                     0
#define ES_LocalModel_ejs_db_validateFormat_options                    1
#define ES_LocalModel_ejs_db_validateNumber_fields                     0
#define ES_LocalModel_ejs_db_validateNumber_options                    1
#define ES_LocalModel_ejs_db_validatePresence_fields                   0
#define ES_LocalModel_ejs_db_validatePresence_options                  1
#define ES_LocalModel_ejs_db_validateRecord_thisType                   0
#define ES_LocalModel_ejs_db_validateRecord__hoisted_1_validation      1
#define ES_LocalModel_ejs_db_validateRecord__hoisted_2_check           2
#define ES_LocalModel_ejs_db_validateRecord__hoisted_3_fields          3
#define ES_LocalModel_ejs_db_validateRecord__hoisted_4_options         4
#define ES_LocalModel_ejs_db_validateRecord__hoisted_5_field           5
#define ES_LocalModel_ejs_db_validateUnique_fields                     0
#define ES_LocalModel_ejs_db_validateUnique_options                    1
#define ES_LocalModel_ejs_db_wrapFilter_fn                             0
#define ES_LocalModel_ejs_db_wrapFilter_options                        1
#define ES_LocalModel_ejs_db_constructor_fields                        0
#define ES_LocalModel_LocalModel_fields                                0


/**
 *   Class property slots for the "HtmlConnector" class 
 */
#define ES_ejs_web_HtmlConnector__origin                               6
#define ES_ejs_web_HtmlConnector_HtmlConnector                         6
#define ES_ejs_web_HtmlConnector_ejs_web_aform                         7
#define ES_ejs_web_HtmlConnector_ejs_web_alink                         8
#define ES_ejs_web_HtmlConnector_ejs_web_button                        9
#define ES_ejs_web_HtmlConnector_ejs_web_buttonLink                    10
#define ES_ejs_web_HtmlConnector_ejs_web_chart                         11
#define ES_ejs_web_HtmlConnector_ejs_web_checkbox                      12
#define ES_ejs_web_HtmlConnector_ejs_web_endform                       13
#define ES_ejs_web_HtmlConnector_ejs_web_flash                         14
#define ES_ejs_web_HtmlConnector_ejs_web_form                          15
#define ES_ejs_web_HtmlConnector_ejs_web_image                         16
#define ES_ejs_web_HtmlConnector_ejs_web_label                         17
#define ES_ejs_web_HtmlConnector_ejs_web_link                          18
#define ES_ejs_web_HtmlConnector_ejs_web_extlink                       19
#define ES_ejs_web_HtmlConnector_ejs_web_list                          20
#define ES_ejs_web_HtmlConnector_ejs_web_mail                          21
#define ES_ejs_web_HtmlConnector_ejs_web_progress                      22
#define ES_ejs_web_HtmlConnector_ejs_web_radio                         23
#define ES_ejs_web_HtmlConnector_ejs_web_script                        24
#define ES_ejs_web_HtmlConnector_ejs_web_status                        25
#define ES_ejs_web_HtmlConnector_ejs_web_stylesheet                    26
#define ES_ejs_web_HtmlConnector_ejs_web_tabs                          27
#define ES_ejs_web_HtmlConnector_getColumns                            28
#define ES_ejs_web_HtmlConnector_ejs_web_table                         29
#define ES_ejs_web_HtmlConnector_ejs_web_text                          30
#define ES_ejs_web_HtmlConnector_ejs_web_textarea                      31
#define ES_ejs_web_HtmlConnector_ejs_web_tree                          32
#define ES_ejs_web_HtmlConnector_getTextKind                           33
#define ES_ejs_web_HtmlConnector_getOptions                            34
#define ES_ejs_web_HtmlConnector_write                                 35
#define ES_ejs_web_HtmlConnector_NUM_CLASS_PROP                        36

/**
 * Instance slots for "HtmlConnector" type 
 */
#define ES_ejs_web_HtmlConnector_nextId                                0
#define ES_ejs_web_HtmlConnector_controller                            1
#define ES_ejs_web_HtmlConnector_NUM_INSTANCE_PROP                     2

/**
 * 
 *    Local slots for methods in type HtmlConnector 
 */
#define ES_ejs_web_HtmlConnector_HtmlConnector_controller              0
#define ES_ejs_web_HtmlConnector_ejs_web_aform_record                  0
#define ES_ejs_web_HtmlConnector_ejs_web_aform_url                     1
#define ES_ejs_web_HtmlConnector_ejs_web_aform_options                 2
#define ES_ejs_web_HtmlConnector_ejs_web_alink_text                    0
#define ES_ejs_web_HtmlConnector_ejs_web_alink_url                     1
#define ES_ejs_web_HtmlConnector_ejs_web_alink_options                 2
#define ES_ejs_web_HtmlConnector_ejs_web_button_value                  0
#define ES_ejs_web_HtmlConnector_ejs_web_button_buttonName             1
#define ES_ejs_web_HtmlConnector_ejs_web_button_options                2
#define ES_ejs_web_HtmlConnector_ejs_web_buttonLink_text               0
#define ES_ejs_web_HtmlConnector_ejs_web_buttonLink_url                1
#define ES_ejs_web_HtmlConnector_ejs_web_buttonLink_options            2
#define ES_ejs_web_HtmlConnector_ejs_web_chart_data                    0
#define ES_ejs_web_HtmlConnector_ejs_web_chart_options                 1
#define ES_ejs_web_HtmlConnector_ejs_web_checkbox_name                 0
#define ES_ejs_web_HtmlConnector_ejs_web_checkbox_value                1
#define ES_ejs_web_HtmlConnector_ejs_web_checkbox_submitValue          2
#define ES_ejs_web_HtmlConnector_ejs_web_checkbox_options              3
#define ES_ejs_web_HtmlConnector_ejs_web_checkbox_checked              4
#define ES_ejs_web_HtmlConnector_ejs_web_flash_kind                    0
#define ES_ejs_web_HtmlConnector_ejs_web_flash_msg                     1
#define ES_ejs_web_HtmlConnector_ejs_web_flash_options                 2
#define ES_ejs_web_HtmlConnector_ejs_web_form_record                   0
#define ES_ejs_web_HtmlConnector_ejs_web_form_url                      1
#define ES_ejs_web_HtmlConnector_ejs_web_form_options                  2
#define ES_ejs_web_HtmlConnector_ejs_web_image_src                     0
#define ES_ejs_web_HtmlConnector_ejs_web_image_options                 1
#define ES_ejs_web_HtmlConnector_ejs_web_label_text                    0
#define ES_ejs_web_HtmlConnector_ejs_web_label_options                 1
#define ES_ejs_web_HtmlConnector_ejs_web_link_text                     0
#define ES_ejs_web_HtmlConnector_ejs_web_link_action                   1
#define ES_ejs_web_HtmlConnector_ejs_web_link_options                  2
#define ES_ejs_web_HtmlConnector_ejs_web_extlink_text                  0
#define ES_ejs_web_HtmlConnector_ejs_web_extlink_url                   1
#define ES_ejs_web_HtmlConnector_ejs_web_extlink_options               2
#define ES_ejs_web_HtmlConnector_ejs_web_list_field                    0
#define ES_ejs_web_HtmlConnector_ejs_web_list_choices                  1
#define ES_ejs_web_HtmlConnector_ejs_web_list_defaultValue             2
#define ES_ejs_web_HtmlConnector_ejs_web_list_options                  3
#define ES_ejs_web_HtmlConnector_ejs_web_list_isSelected               4
#define ES_ejs_web_HtmlConnector_ejs_web_list_i                        5
#define ES_ejs_web_HtmlConnector_ejs_web_list__hoisted_6_choice        6
#define ES_ejs_web_HtmlConnector_ejs_web_list__hoisted_7_field         7
#define ES_ejs_web_HtmlConnector_ejs_web_mail_nameText                 0
#define ES_ejs_web_HtmlConnector_ejs_web_mail_address                  1
#define ES_ejs_web_HtmlConnector_ejs_web_mail_options                  2
#define ES_ejs_web_HtmlConnector_ejs_web_progress_initialData          0
#define ES_ejs_web_HtmlConnector_ejs_web_progress_options              1
#define ES_ejs_web_HtmlConnector_ejs_web_radio_name                    0
#define ES_ejs_web_HtmlConnector_ejs_web_radio_selected                1
#define ES_ejs_web_HtmlConnector_ejs_web_radio_choices                 2
#define ES_ejs_web_HtmlConnector_ejs_web_radio_options                 3
#define ES_ejs_web_HtmlConnector_ejs_web_radio_checked                 4
#define ES_ejs_web_HtmlConnector_ejs_web_radio__hoisted_5_v            5
#define ES_ejs_web_HtmlConnector_ejs_web_radio__hoisted_6_item         6
#define ES_ejs_web_HtmlConnector_ejs_web_script_url                    0
#define ES_ejs_web_HtmlConnector_ejs_web_script_options                1
#define ES_ejs_web_HtmlConnector_ejs_web_status_data                   0
#define ES_ejs_web_HtmlConnector_ejs_web_status_options                1
#define ES_ejs_web_HtmlConnector_ejs_web_stylesheet_url                0
#define ES_ejs_web_HtmlConnector_ejs_web_stylesheet_options            1
#define ES_ejs_web_HtmlConnector_ejs_web_tabs_initialData              0
#define ES_ejs_web_HtmlConnector_ejs_web_tabs_options                  1
#define ES_ejs_web_HtmlConnector_ejs_web_tabs__hoisted_2_t             2
#define ES_ejs_web_HtmlConnector_ejs_web_tabs__hoisted_3_name          3
#define ES_ejs_web_HtmlConnector_ejs_web_tabs__hoisted_4_url           4
#define ES_ejs_web_HtmlConnector_getColumns_data                       0
#define ES_ejs_web_HtmlConnector_getColumns_options                    1
#define ES_ejs_web_HtmlConnector_getColumns_columns                    2
#define ES_ejs_web_HtmlConnector_getColumns__hoisted_3_name            3
#define ES_ejs_web_HtmlConnector_getColumns__hoisted_4_name            4
#define ES_ejs_web_HtmlConnector_ejs_web_table_data                    0
#define ES_ejs_web_HtmlConnector_ejs_web_table_options                 1
#define ES_ejs_web_HtmlConnector_ejs_web_table_originalOptions         2
#define ES_ejs_web_HtmlConnector_ejs_web_table_tableId                 3
#define ES_ejs_web_HtmlConnector_ejs_web_table_columns                 4
#define ES_ejs_web_HtmlConnector_ejs_web_table_refresh                 5
#define ES_ejs_web_HtmlConnector_ejs_web_table_sortOrder               6
#define ES_ejs_web_HtmlConnector_ejs_web_table_sort                    7
#define ES_ejs_web_HtmlConnector_ejs_web_table_styleBody               8
#define ES_ejs_web_HtmlConnector_ejs_web_table_row                     9
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_10_url         10
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_11_name        11
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_12_header      12
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_13_width       13
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_14_r           14
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_15_url         15
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_16_urlOptions  16
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_17_odd         17
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_18_even        18
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_19_col         19
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_20_name        20
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_21_column      21
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_22_styleCell   22
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_23_align       23
#define ES_ejs_web_HtmlConnector_ejs_web_table__hoisted_24_cellUrl     24
#define ES_ejs_web_HtmlConnector_ejs_web_text_name                     0
#define ES_ejs_web_HtmlConnector_ejs_web_text_value                    1
#define ES_ejs_web_HtmlConnector_ejs_web_text_options                  2
#define ES_ejs_web_HtmlConnector_ejs_web_textarea_name                 0
#define ES_ejs_web_HtmlConnector_ejs_web_textarea_value                1
#define ES_ejs_web_HtmlConnector_ejs_web_textarea_options              2
#define ES_ejs_web_HtmlConnector_ejs_web_tree_initialData              0
#define ES_ejs_web_HtmlConnector_ejs_web_tree_options                  1
#define ES_ejs_web_HtmlConnector_getTextKind_options                   0
#define ES_ejs_web_HtmlConnector_getTextKind_kind                      1
#define ES_ejs_web_HtmlConnector_getOptions_options                    0
#define ES_ejs_web_HtmlConnector_write_str                             0


/**
 *   Class property slots for the "GoogleConnector" class 
 */
#define ES_ejs_web_GoogleConnector__origin                             6
#define ES_ejs_web_GoogleConnector_GoogleConnector                     6
#define ES_ejs_web_GoogleConnector_scriptHeader                        7
#define ES_ejs_web_GoogleConnector_ejs_web_table                       8
#define ES_ejs_web_GoogleConnector_ejs_web_chart                       9
#define ES_ejs_web_GoogleConnector_getOptions                          10
#define ES_ejs_web_GoogleConnector_write                               11
#define ES_ejs_web_GoogleConnector_NUM_CLASS_PROP                      12

/**
 * Instance slots for "GoogleConnector" type 
 */
#define ES_ejs_web_GoogleConnector_nextId                              0
#define ES_ejs_web_GoogleConnector_NUM_INSTANCE_PROP                   1

/**
 * 
 *    Local slots for methods in type GoogleConnector 
 */
#define ES_ejs_web_GoogleConnector_GoogleConnector_controller          0
#define ES_ejs_web_GoogleConnector_scriptHeader_kind                   0
#define ES_ejs_web_GoogleConnector_scriptHeader_id                     1
#define ES_ejs_web_GoogleConnector_ejs_web_table_data                  0
#define ES_ejs_web_GoogleConnector_ejs_web_table_options               1
#define ES_ejs_web_GoogleConnector_ejs_web_table_id                    2
#define ES_ejs_web_GoogleConnector_ejs_web_table_columns               3
#define ES_ejs_web_GoogleConnector_ejs_web_table_firstLine             4
#define ES_ejs_web_GoogleConnector_ejs_web_table_goptions              5
#define ES_ejs_web_GoogleConnector_ejs_web_table__hoisted_6_i          6
#define ES_ejs_web_GoogleConnector_ejs_web_table__hoisted_7_name       7
#define ES_ejs_web_GoogleConnector_ejs_web_table__hoisted_8_name       8
#define ES_ejs_web_GoogleConnector_ejs_web_table__hoisted_9_row        9
#define ES_ejs_web_GoogleConnector_ejs_web_table__hoisted_10_col       10
#define ES_ejs_web_GoogleConnector_ejs_web_table__hoisted_11_name      11
#define ES_ejs_web_GoogleConnector_ejs_web_chart_grid                  0
#define ES_ejs_web_GoogleConnector_ejs_web_chart_options               1
#define ES_ejs_web_GoogleConnector_ejs_web_chart_id                    2
#define ES_ejs_web_GoogleConnector_ejs_web_chart_columns               3
#define ES_ejs_web_GoogleConnector_ejs_web_chart_firstLine             4
#define ES_ejs_web_GoogleConnector_ejs_web_chart_col                   5
#define ES_ejs_web_GoogleConnector_ejs_web_chart_dataType              6
#define ES_ejs_web_GoogleConnector_ejs_web_chart_goptions              7
#define ES_ejs_web_GoogleConnector_ejs_web_chart__hoisted_8_name       8
#define ES_ejs_web_GoogleConnector_ejs_web_chart__hoisted_9_row        9
#define ES_ejs_web_GoogleConnector_ejs_web_chart__hoisted_10_col2      10
#define ES_ejs_web_GoogleConnector_ejs_web_chart__hoisted_11_name2     11
#define ES_ejs_web_GoogleConnector_getOptions_options                  0
#define ES_ejs_web_GoogleConnector_getOptions_defaults                 1
#define ES_ejs_web_GoogleConnector_getOptions_result                   2
#define ES_ejs_web_GoogleConnector_getOptions__hoisted_3_word          3
#define ES_ejs_web_GoogleConnector_write_str                           0

#define _ES_CHECKSUM_ejs_web 452641

#endif
